const WA='263784879938';
const EMAIL='info@turoyindustrial.co.zw';
const products=[
{id:'drill',name:'T38 / R32 Drill Bits',category:'Mining Consumables',description:'Heavy-duty button and cross bits for production drilling, development and site maintenance.',price:68,image:'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=1200&q=90',badge:'Popular'},
{id:'roof',name:'Roofbolts & Plates',category:'Mining Consumables',description:'Mechanical and resin roof support components for underground mining applications.',price:39,image:'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&w=1200&q=90'},
{id:'pump',name:'Industrial Dewatering Pump',category:'Plant & Machinery',description:'Robust dewatering and slurry pump solution for mines, construction and industrial sites.',price:690,image:'https://images.unsplash.com/photo-1513828583688-c52646db42da?auto=format&fit=crop&w=1200&q=90',badge:'New'},
{id:'motor',name:'Industrial Electric Motor',category:'Plant & Machinery',description:'Reliable electric motor for pumps, conveyors, workshops and plant equipment.',price:520,image:'https://images.unsplash.com/photo-1531053326607-9d349096d887?auto=format&fit=crop&w=1200&q=90'},
{id:'boots',name:'Steel-Toe Safety Boots',category:'PPE & Safety',description:'Hard-wearing steel-toe safety footwear for mining, fabrication, logistics and construction teams.',price:74,image:'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?auto=format&fit=crop&w=1200&q=90',badge:'PPE'},
{id:'helmet',name:'Industrial Safety Helmet',category:'PPE & Safety',description:'Protective hard hat with comfortable suspension for mining and industrial environments.',price:24,image:'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=1200&q=90'},
{id:'welder',name:'Inverter Welding Machine',category:'Tools & Fabrication',description:'Portable welding unit for workshop repairs, fabrication and field service teams.',price:310,image:'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?auto=format&fit=crop&w=1200&q=90'},
{id:'generator',name:'Diesel Generator 15kVA',category:'Generators & Power',description:'Dependable enclosed 15 kVA diesel generator for mines, workshops, contractors and backup installations.',price:1850,image:'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1200&q=90',badge:'Quote / Buy'},
{id:'rig',name:'Mining / Borehole Drill Rig',category:'Equipment Hire',description:'Heavy-duty mobile drilling rig for boreholes, exploration, DTH and mining-site drilling applications.',price:200,image:'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?auto=format&fit=crop&w=1200&q=90',badge:'Hire'},
{id:'grader',name:'Motor Grader',category:'Equipment Hire',description:'Heavy motor grader for road construction, mine access roads, levelling and site preparation.',price:120,image:'https://images.unsplash.com/photo-1530124566582-a618bc2615dc?auto=format&fit=crop&w=1200&q=90',badge:'Hire'},
{id:'tlb',name:'TLB / Backhoe Loader',category:'Equipment Hire',description:'Versatile tractor-loader-backhoe for excavation, trenching, loading and general construction site work.',price:75,image:'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1200&q=90',badge:'Hire'}
];
const slides=[{tag:'MINING • INDUSTRIAL • ENGINEERING',title:'Your Trusted Mining & Industrial Partner',accent:'Across Zimbabwe',text:'Equipment sales, industrial supplies, PPE, engineering services and nationwide procurement support from Harare.'},{tag:'EQUIPMENT SALES • HIRE • SUPPORT',title:'Built for Tough Sites.',accent:'Ready for Real Work.',text:'Source plant, pumps, tools, power, PPE and site essentials with a team that understands demanding African operations.'},{tag:'PROCUREMENT • SUPPLIERS • DELIVERY',title:'One Industrial Partner.',accent:'More Ways to Buy.',text:'Shop online, request a formal quote, buy through WhatsApp, or apply to join the Turoy supplier network.'}];
let slide=0,timer,typing;let cart=JSON.parse(localStorage.getItem('turoy-cart')||'[]');let installPrompt=null;
const $=q=>document.querySelector(q),$$=q=>[...document.querySelectorAll(q)],money=n=>`US$${n.toFixed(2)}`;
function productCard(p){return `<article class="product-card"><a class="product-image" href="/product.html?id=${p.id}"><img src="${p.image}" alt="${p.name}" loading="lazy">${p.badge?`<span class="badge">${p.badge}</span>`:''}</a><div class="product-body"><span class="product-cat">${p.category}</span><h3><a href="/product.html?id=${p.id}">${p.name}</a></h3><p>${p.description}</p><div class="price-row"><div class="price"><small>${p.category==='Equipment Hire'?'From / hour':'Demo price'}</small><strong>${money(p.price)}</strong></div><button class="add-cart" data-add="${p.id}" aria-label="Add ${p.name} to cart">🛒 Add to Cart</button></div><div class="product-actions"><a class="details-mini" href="/product.html?id=${p.id}">View Product</a><a class="wa-mini" target="_blank" href="https://wa.me/${WA}?text=${encodeURIComponent('Hi Turoy, I need a quote for '+p.name)}">Quote</a></div></div></article>`}
function renderProducts(filter=''){const grid=$('#productGrid');if(!grid)return;const f=filter.toLowerCase();let list=products.filter(p=>(p.name+p.category+p.description).toLowerCase().includes(f));const homepage=location.pathname==='/'||location.pathname.endsWith('/index.html');if(homepage&&!filter)list=[products[4],products[7],products[0],products[2]];grid.innerHTML=list.map(productCard).join('');let more=$('#viewMoreProducts');if(homepage&&!more){more=document.createElement('div');more.id='viewMoreProducts';more.className='view-more-products';more.innerHTML='<a class="btn dark" href="/shop.html">🛍 View More Products →</a>';grid.insertAdjacentElement('afterend',more)}if(more)more.style.display=homepage&&!filter?'flex':'none'}
function save(){localStorage.setItem('turoy-cart',JSON.stringify(cart));renderCart()}function add(id){const p=products.find(x=>x.id===id),x=cart.find(x=>x.id===id);if(!p)return;x?x.qty++:cart.push({...p,qty:1});save();openCart()}
function renderCart(){const count=cart.reduce((a,b)=>a+b.qty,0),total=cart.reduce((a,b)=>a+b.qty*b.price,0);if($('#cartCount'))$('#cartCount').textContent=count;if($('#bottomCartCount'))$('#bottomCartCount').textContent=`Cart (${count})`;if($('#drawerTitle'))$('#drawerTitle').textContent=`${count} item${count===1?'':'s'}`;if($('#subtotal'))$('#subtotal').textContent=money(total);if($('#checkoutTotal'))$('#checkoutTotal').textContent=money(total);if($('#placeOrder'))$('#placeOrder').textContent=`Place Demo Order · ${money(total)}`;if($('#cartItems'))$('#cartItems').innerHTML=cart.length?cart.map(i=>`<div class="cart-line"><img src="${i.image}" alt="${i.name}"><div><h3>${i.name}</h3><span class="money">${money(i.price)}</span><div class="qty"><button data-minus="${i.id}">−</button><b>${i.qty}</b><button data-plus="${i.id}">+</button><button class="remove" data-remove="${i.id}">✕</button></div></div></div>`).join(''):`<div class="empty">🛒<h3>Your cart is empty</h3><p>Add products from the online store to begin your order.</p></div>`;if($('#orderSummary'))$('#orderSummary').innerHTML=cart.map(i=>`<div class="summary-line"><span>${i.qty} × ${i.name}</span><b>${money(i.qty*i.price)}</b></div>`).join('')}
function openCart(){if($('#cartOverlay'))$('#cartOverlay').classList.add('open')}function closeCart(){if($('#cartOverlay'))$('#cartOverlay').classList.remove('open')}
function showSlide(n){if(!$('#heroTitle'))return;slide=(n+slides.length)%slides.length;$$('.hero-slide').forEach((el,i)=>el.classList.toggle('active',i===slide));const s=slides[slide];$('#heroTag').textContent=s.tag;$('#heroTitle').textContent=s.title;$('#heroText').textContent=s.text;$$('#heroDots button').forEach((b,i)=>b.classList.toggle('on',i===slide));clearInterval(typing);let i=0;$('#heroTyped').textContent='';typing=setInterval(()=>{i++;$('#heroTyped').textContent=s.accent.slice(0,i);if(i>=s.accent.length)clearInterval(typing)},65)}
function setupDots(){if($('#heroDots'))$('#heroDots').innerHTML=slides.map((_,i)=>`<button aria-label="Slide ${i+1}" data-slide="${i}" class="${i===0?'on':''}"></button>`).join('')}
function install(){if(installPrompt){installPrompt.prompt();installPrompt.userChoice.finally(()=>installPrompt=null)}else alert('Use your browser menu and choose “Install app” or “Add to Home Screen”.')}
function ensureChat(){if($('#turoyChatLauncher'))return;document.body.insertAdjacentHTML('beforeend',`<div class="chat-panel" id="turoyChat"><button class="chat-close" id="chatClose">×</button><div class="chat-head"><b>Turoy Assistant</b><span>Tell us what you need and we’ll prepare your WhatsApp message.</span></div><div class="chat-form"><input id="chatName" placeholder="Your name"><input id="chatPhone" placeholder="Phone / WhatsApp"><select id="chatNeed"><option value="">What do you need?</option><option>Product enquiry</option><option>Request a quote</option><option>Equipment hire</option><option>Supplier application</option><option>General enquiry</option></select><textarea id="chatMessage" rows="3" placeholder="Tell us what you need..."></textarea><button id="chatSend">Send to WhatsApp</button></div></div><button class="chat-launcher" id="turoyChatLauncher">💬</button>`);$('#turoyChatLauncher').onclick=()=>$('#turoyChat').classList.toggle('open');$('#chatClose').onclick=()=>$('#turoyChat').classList.remove('open');$('#chatSend').onclick=()=>{const name=$('#chatName').value.trim(),phone=$('#chatPhone').value.trim(),need=$('#chatNeed').value,msg=$('#chatMessage').value.trim();const text=`Hello Turoy%0AName: ${encodeURIComponent(name||'Not provided')}%0APhone: ${encodeURIComponent(phone||'Not provided')}%0AEnquiry: ${encodeURIComponent(need||'General enquiry')}%0AMessage: ${encodeURIComponent(msg||'Please contact me.')}`;window.open(`https://wa.me/${WA}?text=${text}`,'_blank')}}
function ensureMobileMenu(){if($('#universalBottomMenu'))return;document.body.insertAdjacentHTML('beforeend',`<nav class="bottom-menu" id="universalBottomMenu"><a href="/"><b>⌂</b><span>Home</span></a><a href="/shop.html"><b>🛍</b><span>Shop</span></a><button id="bottomCart"><b>🛒</b><span id="bottomCartCount">Cart (0)</span></button><a href="/#hire"><b>🚜</b><span>Hire</span></a><button id="bottomInstall"><b>⬇</b><span>Install App</span></button></nav>`);$('#bottomCart').onclick=openCart;$('#bottomInstall').onclick=install}
function ensurePageMenu(){const ph=$('.page-header');if(!ph)return;let nav=$('.page-nav nav');if(nav&&!nav.querySelector('a[href="/"]'))nav.insertAdjacentHTML('afterbegin','<a href="/">Home</a>');if(!$('#pageMenuButton')){const btn=document.createElement('button');btn.id='pageMenuButton';btn.className='menu-button page-menu-button';btn.textContent='☰';$('.page-nav').appendChild(btn);btn.onclick=()=>nav.classList.toggle('open-mobile')}}
function upgradeLinks(){$$('a[href="#products"]').forEach(a=>{if(a.closest('.hero-actions')||a.textContent.includes('Shop')||a.textContent.includes('Browse')||a.textContent.includes('Explore'))a.href='/shop.html'});$$('a[href="#quote"]').forEach(a=>{if(a.textContent.toLowerCase().includes('supplier'))a.href='/supplier.html';else a.href='/quote.html'});$$('a[href="#supplier"]').forEach(a=>a.href='/supplier.html');const supplierBtn=[...document.querySelectorAll('a,button')].find(x=>x.textContent.trim()==='Apply as a Supplier');if(supplierBtn)supplierBtn.onclick=()=>location.href='/supplier.html';$$('[data-form]').forEach(b=>b.onclick=()=>location.href=b.dataset.form==='supplier'?'/supplier.html':'/quote.html');const fb=$('.footer-bottom');if(fb)fb.innerHTML=`© 2026 Turoy Mining & Industrial Supplies. All Rights Reserved. <span class="designer-credit">Website Designed by <a href="https://www.WebDevPro.co.zw" target="_blank">www.WebDevPro.co.zw</a> · <a href="tel:+27812159792">+27 81 215 9792</a></span>`}
document.addEventListener('click',e=>{const t=e.target.closest('[data-add],[data-plus],[data-minus],[data-remove],[data-slide]');if(!t)return;if(t.dataset.add)add(t.dataset.add);if(t.dataset.plus){const x=cart.find(i=>i.id===t.dataset.plus);x.qty++;save()}if(t.dataset.minus){const x=cart.find(i=>i.id===t.dataset.minus);x.qty=Math.max(1,x.qty-1);save()}if(t.dataset.remove){cart=cart.filter(i=>i.id!==t.dataset.remove);save()}if(t.dataset.slide){clearInterval(timer);showSlide(+t.dataset.slide)}});
if($('#productSearch'))$('#productSearch').addEventListener('input',e=>renderProducts(e.target.value));if($('#menuButton'))$('#menuButton').onclick=()=>$('#mobileNav').classList.toggle('open');$$('.mobile-nav a').forEach(a=>a.onclick=()=>$('#mobileNav').classList.remove('open'));if($('#openCart'))$('#openCart').onclick=openCart;if($('#closeCart'))$('#closeCart').onclick=closeCart;if($('#cartOverlay'))$('#cartOverlay').onclick=e=>{if(e.target.id==='cartOverlay')closeCart()};if($('#checkoutButton'))$('#checkoutButton').onclick=()=>{if(!cart.length)return alert('Your cart is empty.');closeCart();location.href='/checkout.html'};if($('#prevSlide'))$('#prevSlide').onclick=()=>{clearInterval(timer);showSlide(slide-1)};if($('#nextSlide'))$('#nextSlide').onclick=()=>{clearInterval(timer);showSlide(slide+1)};if($('#installBtn'))$('#installBtn').onclick=install;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e});setupDots();renderProducts();renderCart();upgradeLinks();ensurePageMenu();ensureMobileMenu();ensureChat();showSlide(0);if($('#heroTitle'))timer=setInterval(()=>showSlide(slide+1),6500);