const WA='263784879938';
const products=[
{id:'drill',name:'T38 / R32 Drill Bits',category:'Mining Consumables',description:'Heavy-duty button and cross bits for production drilling, development and site maintenance.',price:68,image:'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=1000&q=88',badge:'Popular'},
{id:'roof',name:'Roofbolts & Plates',category:'Mining Consumables',description:'Mechanical and resin roof support components for underground mining applications.',price:39,image:'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&w=1000&q=88'},
{id:'pump',name:'Industrial Dewatering Pump',category:'Plant & Machinery',description:'Robust dewatering and slurry pump solution for mines, construction and industrial sites.',price:690,image:'https://images.unsplash.com/photo-1513828583688-c52646db42da?auto=format&fit=crop&w=1000&q=88',badge:'New'},
{id:'motor',name:'Industrial Electric Motor',category:'Plant & Machinery',description:'Reliable electric motor for pumps, conveyors, workshops and plant equipment.',price:520,image:'https://images.unsplash.com/photo-1531053326607-9d349096d887?auto=format&fit=crop&w=1000&q=88'},
{id:'boots',name:'Steel-Toe Safety Boots',category:'PPE & Safety',description:'Hard-wearing safety footwear for mining, fabrication, logistics and construction teams.',price:74,image:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1000&q=88',badge:'PPE'},
{id:'helmet',name:'Industrial Safety Helmet',category:'PPE & Safety',description:'Protective hard hat with comfortable suspension for mining and industrial environments.',price:24,image:'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=1000&q=88'},
{id:'welder',name:'Inverter Welding Machine',category:'Tools & Fabrication',description:'Portable welding unit for workshop repairs, fabrication and field service teams.',price:310,image:'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?auto=format&fit=crop&w=1000&q=88'},
{id:'generator',name:'Diesel Generator 15kVA',category:'Power & Hire',description:'Dependable site power for mines, workshops, contractors and backup installations.',price:1850,image:'https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=1000&q=88',badge:'Quote / Buy'}
];
const slides=[
{tag:'MINING • INDUSTRIAL • ENGINEERING',title:'Your Trusted Mining & Industrial Partner',accent:'Across Zimbabwe',text:'Equipment sales, industrial supplies, PPE, engineering services and nationwide procurement support from Harare.'},
{tag:'EQUIPMENT SALES • HIRE • SUPPORT',title:'Built for Tough Sites.',accent:'Ready for Real Work.',text:'Source plant, pumps, tools, power, PPE and site essentials with a team that understands demanding African operations.'},
{tag:'PROCUREMENT • SUPPLIERS • DELIVERY',title:'One Industrial Partner.',accent:'More Ways to Buy.',text:'Shop online, request a formal quote, buy through WhatsApp, or apply to join the Turoy supplier network.'}
];
let slide=0,timer,typing;let cart=JSON.parse(localStorage.getItem('turoy-cart')||'[]');let installPrompt=null;
const $=q=>document.querySelector(q), $$=q=>[...document.querySelectorAll(q)], money=n=>`US$${n.toFixed(2)}`;
function renderProducts(filter=''){const f=filter.toLowerCase();$('#productGrid').innerHTML=products.filter(p=>(p.name+p.category+p.description).toLowerCase().includes(f)).map(p=>`<article class="product-card"><div class="product-image"><img src="${p.image}" alt="${p.name}">${p.badge?`<span class="badge">${p.badge}</span>`:''}</div><div class="product-body"><span class="product-cat">${p.category}</span><h3>${p.name}</h3><p>${p.description}</p><div class="price-row"><div class="price"><small>Demo price</small><strong>${money(p.price)}</strong></div><button class="add-cart" data-add="${p.id}">🛒 Add to Cart</button></div><a class="wa-mini" target="_blank" href="https://wa.me/${WA}?text=${encodeURIComponent('Hi Turoy, I need a quote for '+p.name)}">💬 Quote on WhatsApp</a></div></article>`).join('');}
function save(){localStorage.setItem('turoy-cart',JSON.stringify(cart));renderCart()}
function add(id){const p=products.find(x=>x.id===id),x=cart.find(x=>x.id===id);x?x.qty++:cart.push({...p,qty:1});save();openCart()}
function renderCart(){const count=cart.reduce((a,b)=>a+b.qty,0),total=cart.reduce((a,b)=>a+b.qty*b.price,0);$('#cartCount').textContent=count;$('#bottomCartCount').textContent=`Cart (${count})`;$('#drawerTitle').textContent=`${count} item${count===1?'':'s'}`;$('#subtotal').textContent=money(total);$('#checkoutTotal').textContent=money(total);$('#placeOrder').textContent=`Place Demo Order · ${money(total)}`;$('#cartItems').innerHTML=cart.length?cart.map(i=>`<div class="cart-line"><img src="${i.image}" alt="${i.name}"><div><h3>${i.name}</h3><span class="money">${money(i.price)}</span><div class="qty"><button data-minus="${i.id}">−</button><b>${i.qty}</b><button data-plus="${i.id}">+</button><button class="remove" data-remove="${i.id}">✕</button></div></div></div>`).join(''):`<div class="empty">🛒<h3>Your cart is empty</h3><p>Add products from the online store to begin your order.</p></div>`;$('#orderSummary').innerHTML=cart.map(i=>`<div class="summary-line"><span>${i.qty} × ${i.name}</span><b>${money(i.qty*i.price)}</b></div>`).join('');}
function openCart(){$('#cartOverlay').classList.add('open')} function closeCart(){ $('#cartOverlay').classList.remove('open') }
function showSlide(n){slide=(n+slides.length)%slides.length;$$('.hero-slide').forEach((el,i)=>el.classList.toggle('active',i===slide));const s=slides[slide];$('#heroTag').textContent=s.tag;$('#heroTitle').textContent=s.title;$('#heroText').textContent=s.text;$$('#heroDots button').forEach((b,i)=>b.classList.toggle('on',i===slide));clearInterval(typing);let i=0;$('#heroTyped').textContent='';typing=setInterval(()=>{i++;$('#heroTyped').textContent=s.accent.slice(0,i);if(i>=s.accent.length)clearInterval(typing)},65)}
function setupDots(){$('#heroDots').innerHTML=slides.map((_,i)=>`<button aria-label="Slide ${i+1}" data-slide="${i}" class="${i===0?'on':''}"></button>`).join('')}
function install(){if(installPrompt){installPrompt.prompt();installPrompt.userChoice.finally(()=>installPrompt=null)}else alert('Use your browser menu and choose “Install app” or “Add to Home Screen”.')}
document.addEventListener('click',e=>{const t=e.target.closest('[data-add],[data-plus],[data-minus],[data-remove],[data-slide],[data-form]');if(!t)return;if(t.dataset.add)add(t.dataset.add);if(t.dataset.plus){const x=cart.find(i=>i.id===t.dataset.plus);x.qty++;save()}if(t.dataset.minus){const x=cart.find(i=>i.id===t.dataset.minus);x.qty=Math.max(1,x.qty-1);save()}if(t.dataset.remove){cart=cart.filter(i=>i.id!==t.dataset.remove);save()}if(t.dataset.slide){clearInterval(timer);showSlide(+t.dataset.slide)}if(t.dataset.form)alert(t.dataset.form==='quote'?'Replace this placeholder with the client’s Quote Google Form URL.':'Replace this placeholder with the client’s Supplier Application Google Form URL.')});
$('#productSearch').addEventListener('input',e=>renderProducts(e.target.value));$('#menuButton').onclick=()=>$('#mobileNav').classList.toggle('open');$$('.mobile-nav a').forEach(a=>a.onclick=()=>$('#mobileNav').classList.remove('open'));$('#openCart').onclick=openCart;$('#bottomCart').onclick=openCart;$('#closeCart').onclick=closeCart;$('#cartOverlay').onclick=e=>{if(e.target.id==='cartOverlay')closeCart()};$('#checkoutButton').onclick=()=>{if(!cart.length)return alert('Your cart is empty.');closeCart();$('#checkoutModal').classList.add('open')};$('#closeCheckout').onclick=()=>$('#checkoutModal').classList.remove('open');$('#checkoutModal').onclick=e=>{if(e.target.id==='checkoutModal')$('#checkoutModal').classList.remove('open')};$('#checkoutForm').onsubmit=e=>{e.preventDefault();alert('Demo checkout complete. Connect the final payment gateway/API to process live payment.')};$('#prevSlide').onclick=()=>{clearInterval(timer);showSlide(slide-1)};$('#nextSlide').onclick=()=>{clearInterval(timer);showSlide(slide+1)};$('#installBtn').onclick=install;$('#bottomInstall').onclick=install;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e});setupDots();renderProducts();renderCart();showSlide(0);timer=setInterval(()=>showSlide(slide+1),6500);
